#!/usr/bin/env bash

# rsd [rsd options] COMMAND [command options]
# rsd [rsd options] --version
# rsd [rsd options] --check-version
# rsd [rsd options] --install PATH
#
# Description:
#   rsd is a generic command loader from the command line
#
#   for commands, actually, are bash functions.
#   the idea is the group classes of commands (or tasks) into modules
#   and let rsd call it to have an organized command line
#
# rsd options [need to be before a `command`]:
#   --usage | --help | -h
#       Display help usage.
#   --version
#       Return the RSD version.
#   --check-version
#       Compares the local version to the one in the repository.
#   --install PATH | MODE
#       Install RSD in the provided PATH or
#       MODE: local or user
#   --debug LEVEL | -d LEVEL
#       Sets the debug level
#   --lib-dir PATHs | -l PATHs | --libdir PATHs | --lib PATHs
#       Coma separated paths to search for libraries.
#   --config-dir PATHs | --config PATHs | -c PATHs
#       Coma separated paths to search for configuration files directories.
#   --no-local | -nl
#       Do not switch to a local rsd copy on the same directory.
#   --completion
#       Support for bash completion.
#       In completion mode, no command or action is actually executed.
#       No command file should exec in global space.
#   --check-mode
#       Returns the mode of the installation of the RSD.
#       unknown: not sure yet
#       distro: installed in the system (e.g. /usr/bin)
#       local: installed in the /usr/local directory
#       user: installed in the user's home directory
#       custom: installed in a custom directory with its own tree structure
#       devel: running from the developement tree
#       not-installed: not installed yet
#   --pass-thru | -pt
#       Pass the rest of the arguments to the shell and run whathever is there.
#   --no-pass-thru | -np
#       Do not pass the rest of the arguments to the shell.
#
# Exit codes:
#   0 - SUCCESS
#   1 - Not bash 4.3
#   2 - Bad usage
#   3 - Program not found
#   4 - There is a new version in the repository
#   5 - Missing
#   6 - Missing system files (maybe not installed)
#   7 - Mismatch information
#   8 - To be done in the future
#   9 - Missing command line argument
#   10 - Command failure (unknown reason)
#   11 - Internal Failure
#   12 - Try to run a library directly
#   13 - Installation failure - Insuficient permissions
#   14 - Installation failure - Failed to create temp directory
#   15 - Installation failure - Failed to clone repository
#   16 - Installation failure - Installion in system directories is not supported

# Note: By default all name space used starts with a rsd:: prefix for functions or
#       RSD_ for variables.  This is to avoid conflicts with other libraries.
#       There will be some basic settings like DEBUG, VERSION, etc.  However, the
#       main idea is to have a clean environment for the commands to be loaded. So it is
#       for external libraries to blindly check it.

# TODO:
#    - [ ] Define better debug level meanings.
#    - [ ] Uninstall
#    - [ ] Completion installation
#    - [ ] Data dir Installation check

shopt -s extglob

RSD_VERSION='1.9.11'
VERSION=$RSD_VERSION

RSD_ON=1

# Initial Debug level.  It will be replaced by command line arguments later on.
# Set to 1 to debug stages before command line argument has a chance to kick in
RSD_DEBUG=0

# TESTING: PASSTHRU is on by default for testing
RSD_PASS_THRU=1

# Note: RSD will load the command file and call the command function as needed.
#       Hoever the script needs to be self independent to download, install or upgrade itself as neeeded.

# RSD_MODE: The mode of the instalation of the RSD.
#           unknown: not sure yet
#           distro: installed in the system (e.g. /usr/bin)
#           local: installed in the /usr/local directory
#           user: installed in the user's home directory
#           custom: installed in a custom directory with its own tree structure
#           devel: running from the developement tree
#           not-installed: not installed yet
RSD_MODE="unknown"
# The latest version of this file in the repository url
RSD_GITHUB_REPO="https://github.com/rsd/rsd.git"
RSD_GITHUB_REPO_BRANCH="2024"

#RSD_LATEST_RSD_REPO="https://raw.githubusercontent.com/rsd/rsd/master/rsd"
RSD_LATEST_RSD_REPO="https://raw.githubusercontent.com/rsd/rsd/2024/rsd"

# if a function returns error, this is the reason
# TODO: write a better API to handle errors
RSD_ERROR_MSG=""
# base path to libraries
RSD_LIBDIR=()
RSD_LIBDIR_temp=()

RSD=$(basename "$0")
RSD_RUN_DIR=$(readlink -f "$(dirname "$0")")

RSD_LOCAL_DIR=$(pwd)
# Commands and action being called
RSD_COMMAND=
RSD_ACTION=

# bash 4.3 required
if [[ "${BASH_VERSINFO[0]}" -lt 4 ]] || [[ "${BASH_VERSINFO[0]}" -eq 4 && "${BASH_VERSINFO[1]}" -lt 3 ]]; then
	echo "Abort! BASH >= 4.3 required.  Got $BASH_VESION" >&2
	exit 1
fi

# Parse Config
declare -A RSD_PARSE_CONFIG=(
    # What to do with unkown options?
    # "ignore" - ignore them (default)
    # "error" - raise an error
    ["unknown-option"]="ignore"
    # Stop processing options on the first command
    # Or keeo processing until the end?
    # This control wheather options with the same name can coehwist and the place where found
    # is imporntant or repeated options are not allowed and they be placed anywhere.
    ["stop-on-command"]=1
)


# paramenters arguments
# 0 => No argument
# 1 => One argument
# unknown defaults to 1
declare -A RSD_ARGS_PARAM=(
    ["debug"]=1
    ["d"]=1
    ["version"]=0
    ["v"]=0
    ["check-version"]=0
    ["lib-dir"]=1
    ["l"]=1
    ["install"]=1
    ["no-local"]=0
    ["nl"]=0
    ["usage"]=0
    ["help"]=0
    ["h"]=0
    ["rsdlib"]=0
    ["completion"]=0
    ["usage"]=0
    ["help"]=0
    ["h"]=0
    ["check-mode"]=0
    ["config-dir"]=1
    ["config"]=1
    ["c"]=1
    ["pass-thru"]=0
    ["pt"]=0
    ["no-pass-thru"]=0
    ["np"]=0
    #["debug-parse-args"]=0 # Internal use
)

# Processed Command Line Arguments for main rsd
declare -A RSD_ARGS
# Processed Command Line Arguments for the command
declare -A RSD_COMMAND_ARGS
# Unprocessed Command Line Arguments
declare -a RSD_ARGS_UNPROCESSED


# Seatch paths
declare -ga RSD_LIBRARY_SEARCH_PATH
declare -ga RSD_CONFIG_LIBRARY_SEARCH_PATH

# Checks if a version is greater than another
# Arguments:
#   $1 - The version to compare
#   $2 - The version to compare to
# Returns:
#   0 - if the first version is greater than the second
#   1 - if the first version is less than the second
function rsd::version_gt() {
	test "$(printf '%s\n' "$@" | sort -V | head -n 1)" != "$1";
}

# Display the usage of the command
function rsd::usage() {
	local command

	echo "$RSD v$RSD_VERSION"
	echo "Usage:"

	if [[ -z "$RSD_COMMAND" ]]; then
		echo -e "\t$RSD [RSD OPTIONS] COMMAND [command options] [ACTION] [action options]"
		echo -e "\t$RSD [RSD OPTIONS] --version"
		echo -e "\t$RSD [RSD OPTIONS] --check-version"
		echo -e "\t$RSD [RSD OPTIONS] --install PATH"
		echo
		echo -e "\tRSD OPTIONS:"
		echo -e "\t\t--usage | --help | -h"
		echo -e "\t\t\tDisplay help usage."
		echo -e "\t\t--version"
		echo -e "\t\t\tReturn the RSD version."
		echo -e "\t\t--check-version"
		echo -e "\t\t\tCompares the local version to the one in the repository."
		echo -e "\t\t--install PATH"
		echo -e "\t\t\tInstall RSD in the provided PATH"
		echo -e "\t\t--debug LEVEL | -d LEVEL"
		echo -e "\t\t\tSets the debug level"
		echo -e "\t\t--lib-dir PATHs | -l PATHs | --libdir PATHs | --lib PATHs"
		echo -e "\t\t\tComa separated paths to search for libraries."
		echo -e "\t\t--config-dir PATHs | --config PATHs | -c PATHs"
		echo -e "\t\t\tComa separated paths to search for configuration files directories."
		echo -e "\t\t--no-local | -nl"
		echo -e "\t\t\tDo not switch to a local rsd copy on the same directory."
		echo -e "\t\t--completion"
		echo -e "\t\t\tSupport for bash completion."
		echo -e "\t\t--check-mode"
        echo -e "\t\t\tReturns the mode of the installation of the RSD."
        echo -e "\t\t\tunknown: not sure yet"
        echo -e "\t\t\tdistro: installed in the system (e.g. /usr/bin)"
        echo -e "\t\t\tlocal: installed in the /usr/local directory"
        echo -e "\t\t\tuser: installed in the user's home directory"
        echo -e "\t\t\tcustom: installed in a custom directory with its own tree structure"
        echo -e "\t\t\tdevel: running from the developement tree"
        echo -e "\t\t\tnot-installed: not installed yet"
        echo -e "\t\t--pass-thru | -pt"
        echo -e "\t\t\tPass the rest of the arguments to the shell and run whathever is there."
        echo -e "\t\t--no-pass-thru | -np"
        echo -e "\t\t\tDo not pass the rest of the arguments to the shell."

		if bash::is_function rsd::list_all_commands; then
            echo -e "\tCommands:"
            for command in $(rsd::list_all_commands); do
                # load right here (if there is a complete installation)
                if bash::is_function rsd::source_lib; then
                    $(rsd::source_lib command/"$command")
                fi
                short_desc="RSD_C_${command^^}_SHORT_DESC"
                short_desc="${!short_desc}"
                echo -e "\t\t$command"
                if [[ -n ${short_desc} ]]; then
                    echo -e "\t\t\t${short_desc}"
                fi
            done
        else
            rsd::debug "rsd::list_all_commands not installed."
		fi
	else
		if bash::is_function rsd::list_all_actions; then
            echo -e "\t$RSD [RSD OPTIONS] $RSD_COMMAND <action> [COMMAND OPTIONS]"
            short_desc="RSD_C_${RSD_COMMAND^^}_SHORT_DESC"
            short_desc="${!short_desc}"
            echo -e "\n\t${short_desc}"

            if actions=$(rsd::list_all_actions "$RSD_COMMAND"); then
                echo -e "\n\tRegistered actions for $RSD_COMMAND:"
                echo "$actions"
            fi

            if bash::is_function rsd::c::"$RSD_COMMAND"::help; then
                echo -e "\t\t$(rsd::c::"$RSD_COMMAND"::help)"
            fi
        else
            echo -e "\t$RSD [RSD OPTIONS] <command> "
		fi
	fi
	echo
}

# Debug to STDOUT
# Arguments:
#   $1 - The message to be displayed
#   $2 - The debug level (default 1)
function rsd::debug() {
	local msg=$1
	shift
	local level=1

	if (($#>0));then
		level=$1
	fi
	if (( RSD_DEBUG >= level )); then
		echo "$level: $msg" >&2
	fi
}

# Same as rsd::debug, but the level comes first, for convenience
# Arguments:
#   $1 - The debug level
#   $* - The message(s) to be displayed
function rsd::debug2() {
	local level=$1
	shift

	if (( RSD_DEBUG >= level )); then
		echo "$level:" "$@" >&2
	fi
}

# outputs a warning message to the STDERR
# Arguments:
#   $1 - The message to be displayed
function rsd::warn() {
    echo "$*" >&2
}

# Finds a bin file in the path
# Arguments:
#   $1 - The file to be found
function rsd::check_binary() {
	local file=$1
	local path
	local IFS=":"

	for path in $PATH; do
		if [[ -f "$path/$file" ]]; then
		return 0
		fi
	done

	RSD_ERROR_MSG="Command $file not in PATH."
	return 1
}

# Checks a list of binaries files in the path
# Arguments:
#   $* - The list of files to be found
# Returns:
#   0 - if all files are found
#   1 - if any file is not found
function rsd::check_binaries() {
	local file
	local path
	local IFS=":"

	for file in "$@";  do
		if ! rsd::check_binary "$file"; then
		return 1
		fi
	done
	return 0
}

# Checks a list of binaries files in the path or aborts
# Usefull if there is no point into continue in the absence of a binary
# Arguments:
#   $* - The list of files to be found
function rsd::check_binaries_or_fail() {
	if ! rsd::check_binaries "$@"; then
		rsd::warn "$RSD_ERROR_MSG"
		exit 3
	fi
	return 0
}

# Parse command line arguments:
# Arguments:
#   $1 - The name of the Associative Array with the configuration [optional]
#   $2 - The name of the Associative Array to be used as a return with processed information
#   $3 - The name of the Array to be used as a return with non-processed information (pass-thru).
#   $* - The command line arguments
# Returns:
#   Associative Array with the parsed arguments
#   0 - if the arguments are parsed
# Attention:
#   This will be run before transfering control to another rsd (newer) installed.
function rsd::parse_args() {
	local config_name=$1
	local param_name=$2
	local unprocessed_name=$3
	shift 3

	local arg
	local count=0

    local has_config=1
    if [[ -z "$config_name" ]]; then
        has_config=0
        declare -A config
    else
        declare -n config="$config_name"
    fi
    declare -n param="$param_name"
    declare -n unprocessed="$unprocessed_name"
    unprocessed=()

    [[ "$RSD_DEBUG" -gt 0 ]] && rsd::warn "rsd::parse_args: Total: $#, Arguments:" "$@"

	while [ $# -gt 0 ]; do
	    [[ "$RSD_DEBUG" -gt 0 ]] && rsd::warn "rsd::parse_args: Processing: $1"

        # If a command has been found and stop-on-command is enabled, terminate option parsing immediately
        if [[ $count -gt 0 && "${RSD_PARSE_CONFIG[stop-on-command]}" -eq 1 ]]; then
            unprocessed+=("$@")
            break
        fi

		case "$1" in
		--)
            shift
            unprocessed+=("$@")
            break
		    ;;
        --*|-*)
            arg=${1#-}
            arg=${arg#-}
            arg=${arg,,}

            if bash::key_exists "$arg" in config; then
                if [[ "${config[$arg]}" -eq 1 ]]; then
                    if [[ -z $2 ]]; then
                        rsd::warn "Error: Missing argument for option $1."
                        exit 9
                    else
                        param[$arg]="$2"
                        shift
                    fi
                else
                    param[$arg]=1
                fi
            elif [[ "$arg" == "debug-parse-args" ]]; then
                # pass ahead
                unprocessed+=("--debug-parse-args")
                param[$arg]=1
            else
                # Handling unrecognized options
                if [[ "${RSD_PARSE_CONFIG[unknown-option]}" == "error" ]]; then
                    rsd::warn "Error: Unrecognized option '$1'."
                    exit 2
                else
                    [[ "$RSD_DEBUG" -gt 0 ]] && rsd::warn "Unrecognized option '$1'. Ignoring here."
                fi
                unprocessed+=("$1")
            fi
            ;;
		*)
            if [[ $count -eq 0 ]]; then
                param[command]="$1"
                [[ "$RSD_DEBUG" -gt 0 ]] && rsd::warn "Got command: $1"
            else
                if [[ "${RSD_PARSE_CONFIG[stop-on-command]}" -eq 1 ]]; then
                    unprocessed+=("$@")
                    break
                fi

                unprocessed+=("$1")
            fi
            ((count++))
            ;;
		esac
		shift
	done

	# Internal Parse Argument Debug
	if [[ "${param[debug-parse-args]}" ]]; then
	    # Deppending on the installation, this might not work at all
	    rsd::warn "Debugging Parse Arguments: $param_name, $unprocessed_name"
	    rsd::create_search_path
	    source "$(rsd::get_libdir_file lib/rsd.lib)"
	    source "$(rsd::get_libdir_file lib/bash_extensions.lib)"
	    bash::dump_associative_array "$param_name"
	    bash::dump_array "$unprocessed_name"
	    rsd::warn "----------------------------------------------------------"
    fi

	return 0
}

# Checks if the key exists in an associative array
# from bash_extensions.lib
# Usage:
#  bash::key_exists {key} in {array}
function bash::key_exists() {
	if [[ "$2" != "in" ]]; then
		rsd::warn "Abort! Incorrect usage of bash::key_exists."
		rsd::warn "Correct usage: bash::key_exists {key} in {array}"
		exit 11
	fi
	eval '[ ${'$3'[$1]+muahaha} ]'
}

# check the latest version in the repository
# Requires:
#  wget, grep, head
# Returns:
#  0 - if the local version is the same or newer
#  1 - if the local version is older
function rsd::check_repository_version() {
	local repo_version
	rsd::check_binaries_or_fail wget grep head

	repo_version=$(wget -q -O - $RSD_LATEST_RSD_REPO | grep ^RSD_VERSION= \
			| head -n 1 | sed -e "s/.*=['\"]\(.*\)['\"]/\1/")

	if rsd::version_gt "$repo_version" "$RSD_VERSION"; then
		RSD_ERROR_MSG="There is a newer version in the repository: $repo_version.  Our version: $RSD_VERSION."
		return 1
	elif [[ $repo_version == "$RSD_VERSION" ]]; then
		RSD_ERROR_MSG="You are using the latest version: $RSD_VERSION."
	else
		RSD_ERROR_MSG="Your version: $RSD_VERSION is newer that the one in the repository: $repo_version."
	fi

	return 0
}

# Search all LIBDIRs for a file and return it on STDOUT
# Returns the first match
# Search order:
# - Each command line argument,
# - Each config option (TODO),
# - Current path,
# - rsd installation dir (if it is a symlink),
# - bash source base,
# - in user's home (TODO) and
# - system wide install (TODO)
# Requires:
#  pwd
# Arguments:
#   $1 - The file to be found
#   $2 - If 1, print the file found
# Returns:
#  0 - if the file is found
#  1 - if the file is not found
function rsd::get_libdir_file() {
	rsd::check_binaries_or_fail pwd readlink
	local file=$1
	local print=${2:-1}
	local libdir
    local key
    local path
    local keys=("." "lib" "command" "config")

	for libdir in "${RSD_LIBRARY_SEARCH_PATH[@]}"; do
	    for key in "${keys[@]}"; do
	        path=$(readlink -f "$libdir/$key")
            if [[ -e "$path/$file" ]]; then
                if ((print)); then
                    echo "$path/$file"
                fi
                return 0
            fi
        done
	done
	return 1
}

# just check if a file exists in LIBDIR
# Arguments:
#   $1 - The file to be found
# Returns:
#  0 - if the file is found
#  1 - if the file is not found
function rsd::check_libdir_file() {
	rsd::get_libdir_file "$1" 0
	return $?
}

#finds the working mode for RSD
function rsd::find_mode() {
    if [[ -d "$RSD_RUN_DIR/.git" ]]; then
        RSD_MODE="devel"
    elif [[ "$RSD_RUN_DIR" == "/usr/local/bin" ]]; then
        RSD_MODE="local"
    elif [[ "$RSD_RUN_DIR" == "/usr/bin" ]]; then
        RSD_MODE="distro"
    elif [[ "$RSD_RUN_DIR" == "$HOME/bin" || "$RSD_RUN_DIR" == "$HOME/.local/bin"  ]]; then
        RSD_MODE="user"
    elif [[ -d "$RSD_RUN_DIR/lib" || -d "$RSD_RUN_DIR/command"  ]]; then
        RSD_MODE="custom"
    else
        RSD_MODE="not-installer"
    fi
}

# Installs the RSD in the provided path or mode
# Arguments:
#   $1 - The path or mode to install
function rsd::install() {
    local install=$1
	rsd::check_binaries_or_fail mktemp git mkdir cp chmod

    if [[ $install == "local" || $install =~ ^/usr/local ]]; then
        install="/usr/local"
    elif [[ $install == "user" ]]; then
        install="$HOME"
    elif [[ $install == "distro" || $install =~ ^/usr/ ]]; then
        rsd::warn "Instaltion in system directories is not supported.  Should be properly packed."
        exit 16
    else
        mkdir -p "$install"
        if [[ $? -ne 0 ]]; then
            rsd::warn "Failed to create installation directory."
            exit 13
        fi
    fi

    if [[ ! -v RSD_INSTALLATION_STEP ]]; then

        # Step 1: Create a secure temporary directory
        TEMP_DIR=$(mktemp -d)
        if [[ ! "$TEMP_DIR" ]]; then
            rsd::warn "Failed to create temp directory."
            exit 14
        fi
        rsd::warn "Created temporary directory $TEMP_DIR."

        # Step 2: Clone the repository into the temporary directory
        rsd::warn "Downloading into $TEMP_DIR."
        git clone --quiet -b "$RSD_GITHUB_REPO_BRANCH" --depth 1 "$RSD_GITHUB_REPO" "$TEMP_DIR"
        if [[ $? -ne 0 ]]; then
            rsd::warn "Failed to clone repository."
            rm -rf "$TEMP_DIR"
            exit 15
        fi

        # Step 3: Check permission and sudo if needed
        if [[ ! -w "$install" ]]; then
            rsd::warn "Insufficient permissions to install to $install."
            if [ $EUID != 0 ]; then
                rsd::warn "Trying ro re-run with sudo."
                RSD_INSTALLATION_STEP=2 exec sudo bash "$TEMP_DIR/rsd" "$@"
            else
                rsd::warn "Even as root, write permission is not available. Check permissions and ownership."
                exit 13
            fi
        else
            RSD_INSTALLATION_STEP=2
        fi
    fi

    if [[ -v RSD_INSTALLATION_STEP && $RSD_INSTALLATION_STEP -eq 2 ]]; then
        # Installation is different for each mode
        case "$install" in
        /usr/local|/usr/local/*)
            # Assuming that for /usr/local the user has write permission, we are in sudo
            PREFIX="/usr/local"
            rsd::warn "Installing in $PREFIX"
            mkdir -p $PREFIX/share/rsd
            mkdir -p $PREFIX/etc/rsd
            cp "$TEMP_DIR/rsd" $PREFIX/bin/
            chmod +x $PREFIX/bin/rsd
            cp -r "$TEMP_DIR/lib" $PREFIX/share/rsd
            cp -r "$TEMP_DIR/command" $PREFIX/share/rsd
            cp -r "$TEMP_DIR/data" $PREFIX/share/rsd
            cp "$TEMP_DIR/LICENSE" $PREFIX/share/rsd
            cp "$TEMP_DIR/README.md" $PREFIX/share/rsd
            cp "$TEMP_DIR/config/rsd.conf" $PREFIX/etc/rsd
            ;;
        $HOME|$HOME/*)
            PREFIX="$HOME/.local"
            rsd::warn "Installing in $PREFIX"
            mkdir -p $PREFIX/share/rsd
            mkdir -p $PREFIX/bin
            mkdir -p $HOME/.config/rsd
            cp "$TEMP_DIR/rsd" $PREFIX/bin/
            chmod +x $PREFIX/bin/rsd
            cp -r "$TEMP_DIR/lib" $PREFIX/share/rsd
            cp -r "$TEMP_DIR/command" $PREFIX/share/rsd
            cp -r "$TEMP_DIR/data" $PREFIX/share/rsd
            cp "$TEMP_DIR/LICENSE" $PREFIX/share/rsd
            cp "$TEMP_DIR/README.md" $PREFIX/share/rsd
            cp "$TEMP_DIR/config/rsd.conf" $HOME/.config/rsd
            ;;
        *)
            echo Skipping for now $HOME vs $install.
            exit 0
            rsd::warn "Installalling in custom directory: $install."
            cp -r "$TEMP_DIR/"* "$install"
            chmod +x "$install/rsd"
            ;;
        esac
        exit 0
    fi
}

# Creates the list of search paths for the libraries
function rsd::create_search_path() {
    declare -ga RSD_LIBRARY_SEARCH_PATH
    local key
    local keys=("lib-dir" "l" "libdir" "lib")

    for key in "${keys[@]}"; do
        if bash::key_exists "$key" in RSD_ARGS; then
            IFS=',' read -r -a RSD_LIBDIR_temp <<< "${RSD_ARGS[$key]}"
            RSD_LIBDIR=("${RSD_LIBDIR[@]}" "${RSD_LIBDIR_temp[@]}")
        fi
    done

    # Command line arguments have precedence over the configuration file
    RSD_LIBRARY_SEARCH_PATH+=("${RSD_LIBDIR[@]}")

    # Here comes the ones from the config files, only in the second run
    RSD_LIBRARY_SEARCH_PATH+=("${RSD_CONFIG_LIBRARY_SEARCH_PATH[@]}")

    # Dev comes first
    if [[ $RSD_MODE == "devel" ]]; then
        RSD_LIBRARY_SEARCH_PATH+=("$RSD_RUN_DIR")
    fi

    # user stuff should have precedence over system stuff
    RSD_LIBRARY_SEARCH_PATH+=("$HOME/.local/share/rsd")
    RSD_LIBRARY_SEARCH_PATH+=("$HOME/.rsd")

    # What is system now depends on the mode we are operating
    if [[ $RSD_MODE == "local" ]]; then
        RSD_LIBRARY_SEARCH_PATH+=("/usr/local/share/rsd")
    elif [[ $RSD_MODE == "opt" ]]; then
        #FIXME:  No opt installation yet
        RSD_LIBRARY_SEARCH_PATH+=("/opt/rsd")
    elif [[ $RSD_MODE == "distro" ]]; then
        RSD_LIBRARY_SEARCH_PATH+=("/usr/share/rsd")
    fi

    # Where RSD is
    RSD_LIBRARY_SEARCH_PATH+=("$RSD_RUN_DIR")
    # Add the current working directory
    RSD_LIBRARY_SEARCH_PATH+=("$(pwd)")

    # Add the directories containing all sourced scripts or parent scripts
    RSD_LIBRARY_SEARCH_PATH+=("$(dirname "${BASH_SOURCE[0]:-.}")")

    # Print all paths in the array for debugging
    #printf "Library Search Paths for $RSD_MODE:\n%s\n" "${RSD_LIBRARY_SEARCH_PATH[@]}"
}

# __main__
# FIXME: as a recursive command calling, this is worked outside a function (for now at least)

# preserves arguments
RSD_ORIGINAL_ARGS=("$0" "${@}")
rsd::find_mode
rsd::parse_args RSD_ARGS_PARAM RSD_ARGS RSD_ARGS_UNPROCESSED $*

# import rsd::debug level
if [[ ${RSD_ARGS[debug]} ]]; then
	RSD_DEBUG=${RSD_ARGS[debug]}
elif [[ ${RSD_ARGS[d]} ]]    ; then
	RSD_DEBUG=${RSD_ARGS[d]}
fi
DEBUG=$RSD_DEBUG

rsd::debug "Debug set to $RSD_DEBUG" 2
rsd::debug2 9 "Arguments parsed (values): keys -> (${RSD_ARGS[*]}): " "${!RSD_ARGS[*]}"
rsd::debug "Original call was ${RSD_ORIGINAL_ARGS[*]}" 7

# swith to a local copy if any (local == pwd)
if ! [[ ${RSD_ARGS[no-local]} || ${RSD_ARGS[nl]} ]]; then
	rsd::debug2 20 "RUN DIR: $RSD_RUN_DIR, LOCAL DIR: $RSD_LOCAL_DIR"
	if [[ "$RSD_RUN_DIR" != "$RSD_LOCAL_DIR" ]]; then
		RSD_LOCAL_RSD="$RSD_LOCAL_DIR/$RSD"
		if [[ -x  "$RSD_LOCAL_RSD" ]]; then
            #get version
            RSD_LOCAL_VERSION=$( $RSD_LOCAL_RSD --version)
            if rsd::version_gt "$RSD_LOCAL_VERSION" $VERSION; then
                if [[ -z ${RSD_ARGS[completion]} ]]; then
                    rsd::warn "Switching to pwd version (-nl to avoid)."
                fi
                $RSD_LOCAL_RSD "$@"
                exit 0
            fi
		fi
	fi
fi

# version
if [[ ${RSD_ARGS[version]} || ${RSD_ARGS[v]} ]]; then
	echo $RSD_VERSION
	exit 0
fi

if [[ ${RSD_ARGS[check-mode]} ]]; then
	echo $RSD_MODE
	exit 0
fi

# downloads and install
# check version
if [[ ${RSD_ARGS[install]} ]]; then
    rsd::install ${RSD_ARGS[install]}
fi

rsd::create_search_path

if ! rsd::check_libdir_file lib/rsd.lib; then
	rsd::warn "Abort! Could not find libdir.  Maybe it need to be installed --install (TODO)."
	exit 5
fi

# library to be loaded from outside (e.g. completion)
if [[ -n "${RSD_ARGS[rsdlib]}" ]]; then
	echo "$(rsd::get_libdir_file lib/rsd.lib)"
	exit 0
fi

# check version
if [[ ${RSD_ARGS[check-version]} ]]; then
	if ! rsd::check_repository_version; then
		echo "$RSD_ERROR_MSG"
		exit 4
	else
		echo "$RSD_ERROR_MSG"
		exit 0
	fi
fi

if [[ ${RSD_ARGS[pass-thru]} || ${RSD_ARGS[pt]} ]]; then
    RSD_PASS_THRU=1
elif [[ ${RSD_ARGS[no-pass-thru]} || ${RSD_ARGS[np]} ]]; then
    RSD_PASS_THRU=0
fi

# load our main library
# after this point there is a need to the full installation
#Now load our defaults
source "$(rsd::get_libdir_file lib/rsd.lib)"

if rsd::check_libdir_file lib/bash_extensions.lib; then
	source "$(rsd::get_libdir_file lib/bash_extensions.lib)"
else
	rsd::warn "Abort! Missing bash extensions library."
	exit 5
fi

# help and usage
if [[ ${RSD_ARGS[usage]} || ${RSD_ARGS[help]} || ${RSD_ARGS[h]} ]]; then
	rsd::usage
	exit 0
fi

# No Command or completion
if [[ -z "${RSD_ARGS[command]}" && ! ${RSD_ARGS[completion]} ]]; then
    rsd::usage
    exit 2
fi

if [[ "${RSD_ARGS[command]}" ]]; then
    # Check if target is a remote target spec (starts with @ or matches user@host)
    if [[ "${RSD_ARGS[command]}" =~ ^@ || "${RSD_ARGS[command]}" =~ .@. ]]; then
        RSD_REMOTE_TARGET="${RSD_ARGS[command]}"

        # real command is the first unprocessed argument
        if [[ ${#RSD_ARGS_UNPROCESSED[@]} -eq 0 ]]; then
            rsd::warn "Error: Remote target specified, but no command provided."
            rsd::usage
            exit 2
        fi

        RSD_COMMAND="${RSD_ARGS_UNPROCESSED[0]}"
        RSD_ARGS_UNPROCESSED=("${RSD_ARGS_UNPROCESSED[@]:1}")

        # 1. Precedence 1: Explicit Double-Dash Skip Indicator
        if [[ "$RSD_COMMAND" == "--" ]]; then
            if [[ ${#RSD_ARGS_UNPROCESSED[@]} -eq 0 ]]; then
                rsd::warn "Error: Double-dash skip specified, but no command payload followed."
                exit 2
            fi
            RSD_COMMAND="${RSD_ARGS_UNPROCESSED[0]}"
            RSD_ARGS_UNPROCESSED=("${RSD_ARGS_UNPROCESSED[@]:1}")

            rsd::debug "Double-dash skip detected. Direct remote pass-through for '$RSD_COMMAND'" 10
            source "$(rsd::get_libdir_file lib/remote.lib)"
            rsd::l::remote::execute "$RSD_REMOTE_TARGET" "$RSD_COMMAND" "${RSD_ARGS_UNPROCESSED[@]}"
            exit $?
        fi

        rsd::debug "Remote execution target: $RSD_REMOTE_TARGET, command payload: $RSD_COMMAND" 15

        # 2. Precedence 2: RSD Custom Command Script Execution
        if command_source=$(rsd::load_command_file "$RSD_COMMAND"); then
            source "$command_source" "${RSD_ARGS_UNPROCESSED[@]}"

            # Route dynamically depending on command's remote awareness
            is_aware="RSD_C_${RSD_COMMAND^^}_REMOTE_AWARE"
            if [[ "${!is_aware}" -eq 1 ]]; then
                rsd::debug "Command $RSD_COMMAND is remote-aware (Mode A Local Orchestration)." 15
                rsd::command "$RSD_COMMAND"
                exit $?
            else
                rsd::debug "Command $RSD_COMMAND is remote-naive (Mode B Remote Delegation fallback)." 15
                source "$(rsd::get_libdir_file lib/remote.lib)"
                local rsd_bin="rsd"
                rsd::l::remote::bootstrap_check "$RSD_REMOTE_TARGET" rsd_bin || exit $?
                rsd::l::remote::execute "$RSD_REMOTE_TARGET" "$rsd_bin" "$RSD_COMMAND" "${RSD_ARGS_UNPROCESSED[@]}"
                exit $?
            fi
        else
            # 3. Precedence 3: Fallback Raw Pass-Through (No custom command script exists)
            rsd::debug "No custom RSD script found for '$RSD_COMMAND'. Triggering raw remote pass-through." 15
            source "$(rsd::get_libdir_file lib/remote.lib)"
            rsd::l::remote::execute "$RSD_REMOTE_TARGET" "$RSD_COMMAND" "${RSD_ARGS_UNPROCESSED[@]}"
            exit $?
        fi
    else
        # Standard Local Execution
        RSD_COMMAND="${RSD_ARGS[command]}"
        rsd::debug "Using command $RSD_COMMAND" 15

        # import the calling command script
        if ! command_source=$(rsd::load_command_file "$RSD_COMMAND"); then
            rsd::debug2 20 "Could not load command $RSD_COMMAND"
            if [[ $RSD_PASS_THRU -eq 1 ]]; then
                rsd::debug "Command '$RSD_COMMAND' not found!" 10
                rsd::debug "Passing through to the shell." 10
                rsd::passthru "$RSD_COMMAND" "${RSD_ARGS_UNPROCESSED[@]}"
                exit 0
            else
                rsd::warn "Command '$RSD_COMMAND' not found!" 0
                RSD_COMMAND=
                rsd::usage
                exit 2
            fi
        fi

        source "$command_source" "${RSD_ARGS_UNPROCESSED[@]}"
        rsd::command "$RSD_COMMAND"

        exit 0
    fi
fi

# Should not get here
exit 11
