#!/usr/bin/env bash

if [[ ! -v RSD_ON || $RSD_ON -ne 1 ]]; then
    echo "This is a RSD library file. It should not be executed directly."
    echo "Please call 'rsd' to use it."
    exit 12
fi

# Companion utility for bash_completion script
# or any completion

RSD_COMMAND_COMPLETION_VERSION="0.1.3"


# List all rsd options
function rsd::c::completion::list-rsd-options() {
	rsd::list_all_options
}

function rsd::c::completion::list-commands() {
    rsd::debug "Listing all commands"
	rsd::list_all_commands
}

function rsd::c::completion::list-command-options() {
	rsd::arguments_or_usage 1 $@
	local command=$1
	local _rsd_source
	
	if ! _rsd_source=$(rsd::load_command_file $command); then
 		rsd::io::warn "Command $command not found"
		exit 10
	fi
	
	source "$_rsd_source"
	
	rsd::list_command_options $command
}

function rsd::c::completion::list-command-actions() {
	rsd::arguments_or_usage 1 $@
	local command=$1
	local _rsd_source
	
	if ! _rsd_source=$(rsd::load_command_file $command); then
		rsd::io::warn "Command $command not found"
		exit 10
	fi
	
	source "$_rsd_source"
	
	rsd::list_all_actions_bare 0 $command
}

function rsd::c::completion::check-rsd-option-has-value() {
	rsd::arguments_or_usage 1 $@
	local option=$1

	if [[ ${RSD_ARGS_PARAM[$option]} == "1" ]]; then
		exit 0
	fi
	exit 1
}

function rsd::c::completion::check-command-option-has-value() {
	rsd::arguments_or_usage 2 $@
	local command=$1
	local option=$2
	local _rsd_source _option
	local options="RSD_COMMAND_${command^^}_ARGS_PARAM"
	
	declare -n _option=$options
	
	if ! _rsd_source=$(rsd::load_command_file $command); then
		rsd::io::warn "Command $command not found"
		exit 10
	fi	
	source "$_rsd_source"
	
	if [[ "${_option[$option]}" == "1" ]]; then
		exit 0
	fi
	exit 1
}
