#!/usr/bin/env bash

if [[ ! -v RSD_ON || $RSD_ON -ne 1 ]]; then
    echo "This is a RSD library file. It should not be executed directly."
    echo "Please call `rsd` to use it."
    exit 12
fi

$(rsd::source_lib_or_die lib/gpg.lib)

RSD_C_GPG_SHORT_DESC="GPG Integration"

rsd::c::gpg::help() {
    echo -e "\n\tGPG Commanf Help:\n"
    echo -e "\t\tActions:"
    echo -e "\t\t\tcheck   Checks the GPG Installation"
    echo -e "\t\t\tinit    Initialize GPG"
    echo -e "\t\t\tencrypt Encrypt a file"
    echo -e "\t\t\tdecrypt Decrypt a file"
}

rsd::c::gpg::check() {
    if ! rsd::check_binary gpg; then
        rsd::warn "GPG is not installed. Please install it first."
        exit 3
    fi

    echo "GPG is installed and ready for use."
}

rsd::c::gpg::init() {
    rsd::check_binaries_or_fail gpg
    echo "init..."
}