#!/usr/bin/env bash

if [[ ! -v RSD_ON || $RSD_ON -ne 1 ]]; then
    echo "This is a RSD library file. It should not be executed directly."
    echo "Please call 'rsd' to use it."
    exit 12
fi

[[ "$RSD_GPG_LIB" != "1" ]] && $(rsd::source_lib_or_die lib/gpg.lib)

RSD_C_GPG_SHORT_DESC="GPG Integration"
RSD_C_GPG_VERSION="0.1.0"

function rsd::c::gpg::help() {
    echo -e "\n\tGPG Command Help:\n"
    echo -e "\t\tActions:"
    echo -e "\t\t\tcheck        Checks the GPG Installation"
    echo -e "\t\t\tinit         Initialize GPG"
    echo -e "\t\t\tencrypt-file  Encrypts (and sign) a file"
    echo -e "\t\t\tdecrypt-file  Decrypt a file"
}

function rsd::c::gpg::check() {
    if rsd::l::gpg::check 1; then
        rsd::io::ok "GPG is installed and working."
        return 0
    else
        return $?
    fi
}

function rsd::c::gpg::init() {
    rsd::check_binaries_or_fail gpg
    echo "init..."
}

function rsd::c::gpg::create-key() {
    rsd::check_binaries_or_fail gpg

    rsd::io::status "Generating a new GPG key for RSD usage."
    rsd::io::info "You will be prompt for a secure strong password from the gpg command."
    rsd::io::info "It will be created under the user id: $RSD_GPG_USER_ID."
    rsd::io::info "These process will be done in 2 parts:"
    rsd::io::info "1. Create the key with certifying capability."
    rsd::io::info "2. Create a sub key with encryption capability."
    rsd::io::blank

    rsd::l::gpg::get_keys $RSD_GPG_USER_ID _r_gpg_keys
    if [[ -n "${_r_gpg_keys[0]}" ]]; then
        rsd::io::warn "There is already a GPG key for RSD usage. Please remove it first."
        exit 3
    fi

    gpg --quick-generate-key $RSD_GPG_USER_ID ed25519 cert,sign 0
    rsd::l::gpg::get_keys $RSD_GPG_USER_ID _r_gpg_keys

    rsd::io::info "Fingerprint: ${_r_gpg_keys[0]}"
    rsd::io::blank

    if [[ -z "${_r_gpg_keys[0]}" ]]; then
        rsd::io::error "Failed to create the GPG key with the user id: '$RSD_GPG_USER_ID'."
        rsd::io::info "You will have to check and clean up (sorry) and then try again."
        exit 3
    fi
    rsd::io::blank
    rsd::io::status "Creating now the sub key for encryption."
    gpg --quick-add-key ${_r_gpg_keys[0]} cv25519 encr 0
    return 0
}

function rsd::c::gpg::encrypt-file() {
    rsd::arguments_or_usage 1 "$@"
    local file="$1"
    rsd::l::gpg::encrypt_file "$file"
    return $?
}

function rsd::c::gpg::decrypt-file() {
    rsd::arguments_or_usage 1 "$@"
    local file="$1"
    rsd::l::gpg::decrypt_file "$file"
    return $?
}
