#!/usr/bin/env bash

if [[ ! -v RSD_ON || $RSD_ON -ne 1 ]]; then
    echo "This is a RSD library file. It should not be executed directly."
    echo "Please call `rsd` to use it."
    exit 12
fi

RSD_COMMAND_TEST_VERSION='0.2.1'

declare -A RSD_COMMAND_TEST_ARGS_PARAM=( ["teste"]=0 ["test"]=1 ["full"]=1 )


function rsd::c::test::test2() {
	echo "Inside Test comannd function."
	echo "Still have these arguments to process:" $@
}

function rsd::c::test::action::test() {
	echo Teste: $@
	rsd::debug "Debug no level"
	rsd::debug "Debug level 1 " 1
	rsd::debug "Debug level 2 " 2
	rsd::debug "Debug level 3 " 3
	rsd::debug "Debug level 4 " 4
}


function rsd::c::test::action::test_argument() {
	echo "Full Arguments before: "$@
	rsd::arguments_or_usage 1 $@
	echo "Full Arguments after: "$@
}
