# Config files are just Bash files sourced by the main script

# FIXME: Config has to be of less precedence than command line argume
#RSD_DEBUG=0

# RSD_CONFIG_LIBRARY_SEARCH_PATH is an array of directories to search for libraries
# it takes preference over the default search path, just command line takes precence over this
# You can add as many as desired.
#RSD_CONFIG_LIBRARY_SEARCH_PATH+=("/var/lib/rsd")

# RSD_CONFIG_CONFIG_SEARCH_PATH is an array of directories to search for configs
# It is a little more tricker as the rsd.conf (this file) was already found.
# However it will take precedence for the rest of the config files
# You can add as many as desired.
#RSD_CONFIG_CONFIG_SEARCH_PATH+=("/etc/rsd")
